package com.sembulung.navigator;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.os.*;import android.view.Gravity;import android.widget.*;import java.util.Locale;
public class MarineMapActivity extends Activity implements LocationListener{
 private static final int R=1301;private static final long F=5000;private LocationManager lm;private Location phone;private NmeaDataStore.Snapshot n;private MarineTileLoader loader;private MarineMapView map;private TextView gps,nmea,depth;private Button source;private int mode=0;private final Handler h=new Handler(Looper.getMainLooper());private final Runnable tick=new Runnable(){public void run(){refresh();h.postDelayed(this,500);}};
 protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(3,27,61));getWindow().setNavigationBarColor(Color.rgb(3,27,61));lm=(LocationManager)getSystemService(LOCATION_SERVICE);FrameLayout root=new FrameLayout(this);loader=new MarineTileLoader(this,()->{if(map!=null)map.postInvalidate();});map=new MarineMapView(this,loader);root.addView(map,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(dp(10),dp(10),dp(10),0);TextView title=chip("SEMBULUNG MARINE",15,true);title.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);top.addView(title,new LinearLayout.LayoutParams(-2,dp(38)));LinearLayout row=new LinearLayout(this);gps=chip("GPS --",10,true);nmea=chip("NMEA --",10,true);depth=chip("DEPTH --",10,true);row.addView(gps,chipLp());row.addView(nmea,chipLp());row.addView(depth,chipLp());top.addView(row,new LinearLayout.LayoutParams(-1,dp(38)));FrameLayout.LayoutParams tlp=new FrameLayout.LayoutParams(-1,-2);tlp.gravity=Gravity.TOP;root.addView(top,tlp);
  LinearLayout right=new LinearLayout(this);right.setOrientation(LinearLayout.VERTICAL);Button plus=floating("+",22);plus.setOnClickListener(v->map.zoom(1));right.addView(plus,square());Button center=floating("◎",20);center.setOnClickListener(v->recenter());right.addView(center,square());Button minus=floating("−",22);minus.setOnClickListener(v->map.zoom(-1));right.addView(minus,square());FrameLayout.LayoutParams rlp=new FrameLayout.LayoutParams(-2,-2);rlp.gravity=Gravity.END|Gravity.CENTER_VERTICAL;rlp.setMargins(0,0,dp(10),0);root.addView(right,rlp);
  source=floating("AUTO",12);source.setOnClickListener(v->{mode=(mode+1)%3;refresh();});FrameLayout.LayoutParams slp=new FrameLayout.LayoutParams(dp(88),dp(44));slp.gravity=Gravity.START|Gravity.BOTTOM;slp.setMargins(dp(12),0,0,dp(30));root.addView(source,slp);Button menu=floating("☰",18);menu.setOnClickListener(v->menu());FrameLayout.LayoutParams mlp=new FrameLayout.LayoutParams(dp(50),dp(50));mlp.gravity=Gravity.END|Gravity.BOTTOM;mlp.setMargins(0,0,dp(12),dp(28));root.addView(menu,mlp);
  TextView att=chip("© OpenStreetMap contributors • Seamarks © OpenSeaMap",8,false);FrameLayout.LayoutParams alp=new FrameLayout.LayoutParams(-2,dp(22));alp.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;alp.setMargins(0,0,0,dp(4));root.addView(att,alp);setContentView(root);startGps();refresh();}
 private void menu(){String s=map.seamarks()?"Sembunyikan seamarks":"Tampilkan seamarks";String[] a={s,"Peta MBTiles lokal","SONAR / NMEA","AIS • CPA / TCPA","Dashboard"};new AlertDialog.Builder(this).setTitle("Marine Map").setItems(a,(d,w)->{if(w==0)map.seamarks(!map.seamarks());else if(w==1)startActivity(new Intent(this,OfflineMapActivity.class));else if(w==2)startActivity(new Intent(this,NmeaActivity.class));else if(w==3)startActivity(new Intent(this,AisActivity.class));else finish();}).show();}
 private void startGps(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},R);return;}if(!lm.isProviderEnabled(LocationManager.GPS_PROVIDER))return;lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,1000,.5f,this);Location x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(x!=null)onLocationChanged(x);}
 public void onLocationChanged(Location x){phone=x;refresh();}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){refresh();}public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==R&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startGps();}
 private boolean nf(){return n!=null&&n.positionFresh(F);}private boolean useN(){return mode==2?nf():mode==0&&nf();}private Double lat(){if(mode==2)return nf()?n.lat:null;if(useN())return n.lat;return phone==null?null:phone.getLatitude();}private Double lon(){if(mode==2)return nf()?n.lon:null;if(useN())return n.lon;return phone==null?null:phone.getLongitude();}private Double hdg(){if(useN()&&n.headingFresh(F))return n.heading;if(mode!=2&&phone!=null&&phone.hasBearing())return(double)phone.getBearing();return null;}
 private void refresh(){n=NmeaDataStore.read(this);if(phone!=null){String a=phone.hasAccuracy()?String.format(Locale.US,"%.0fm",phone.getAccuracy()):"--";gps.setText("GPS "+a);gps.setAlpha(mode==2?.55f:1);}else{gps.setText("GPS --");gps.setAlpha(.55f);}boolean live=n!=null&&n.packetFresh(F);nmea.setText(live?"NMEA LIVE":"NMEA --");nmea.setAlpha(live?1:.55f);if(n!=null&&n.depthFresh(F)){depth.setText(String.format(Locale.US,"DEPTH %.1fm",n.depth));depth.setAlpha(1);}else{depth.setText("DEPTH --");depth.setAlpha(.55f);}source.setText(mode==0?"AUTO":mode==1?"GPS":"NMEA");source.setAlpha(mode==2&&!nf()?.55f:1);map.vessel(lat(),lon(),hdg(),useN(),true);}
 private void recenter(){if(lat()==null||lon()==null){Toast.makeText(this,"Posisi belum tersedia",Toast.LENGTH_SHORT).show();startGps();return;}map.recenter();}
 protected void onResume(){super.onResume();if(lm!=null&&map!=null)startGps();h.removeCallbacks(tick);h.post(tick);}protected void onPause(){super.onPause();h.removeCallbacks(tick);try{if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)lm.removeUpdates(this);}catch(Exception e){}}protected void onDestroy(){h.removeCallbacks(tick);if(loader!=null)loader.close();super.onDestroy();}
 private TextView chip(String t,int s,boolean bold){TextView v=new TextView(this);v.setText(t);v.setTextColor(Color.WHITE);v.setTextSize(s);v.setGravity(Gravity.CENTER);v.setPadding(dp(8),dp(3),dp(8),dp(3));if(bold)v.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);v.setBackground(bg());return v;}private Button floating(String t,int s){Button b=new Button(this);b.setText(t);b.setTextSize(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setPadding(0,0,0,0);b.setMinWidth(0);b.setMinHeight(0);b.setBackground(bg());return b;}private GradientDrawable bg(){GradientDrawable d=new GradientDrawable();d.setColor(0xb809213b);d.setCornerRadius(dp(14));d.setStroke(dp(1),0x4478a9d1);return d;}private LinearLayout.LayoutParams chipLp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(34),1);p.setMargins(dp(2),0,dp(2),0);return p;}private LinearLayout.LayoutParams square(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(46),dp(46));p.setMargins(0,dp(3),0,dp(3));return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}